// test-tokenizer: parity tests for iian::Tokenizer against llama.cpp's llama-tokenize.
//
//   test-tokenizer <model.gguf> [expected.parse.txt] [expected.noparse.txt]
//
// (a) encode -> decode round trip over tests/tokenizer/corpus.txt (parse_special = true and false)
// (b) exact token-id equality with llama-tokenize output (files generated by gen_expected.sh)
// (c) IncrementalDetokenizer == decode(), including byte tokens that split UTF-8 sequences
// (d) special-token API sanity (BOS/EOS/EOG, control filtering, text_to_token, chat_template)
//
// Corpus path: env IIAN_TOKENIZER_CORPUS, else the compile-time default (tests/tokenizer/corpus.txt).
#include "iian/tokenizer.h"

#include "gguf.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using iian::token_t;

static int g_fail = 0;
static int g_pass = 0;

#define CHECK(cond, ...) do { if (cond) { g_pass++; } else { g_fail++; printf("  FAIL %s:%d: ", __FILE__, __LINE__); printf(__VA_ARGS__); printf("\n"); } } while (0)

// same escape processing as llama.cpp common/string_process_escapes (used by llama-tokenize)
static std::string unescape(const std::string & in) {
    std::string out;
    out.reserve(in.size());
    for (size_t i = 0; i < in.size(); ++i) {
        if (in[i] == '\\' && i + 1 < in.size()) {
            switch (in[++i]) {
                case 'n':  out += '\n'; break;
                case 'r':  out += '\r'; break;
                case 't':  out += '\t'; break;
                case '\'': out += '\''; break;
                case '"':  out += '"';  break;
                case '\\': out += '\\'; break;
                case 'x':
                    if (i + 2 < in.size()) {
                        const char x[3] = { in[i + 1], in[i + 2], 0 };
                        char * err = nullptr;
                        const long val = std::strtol(x, &err, 16);
                        if (err == x + 2) {
                            i += 2;
                            out += (char) val;
                            break;
                        }
                    }
                    // fall through
                default:
                    out += '\\';
                    out += in[i];
                    break;
            }
        } else {
            out += in[i];
        }
    }
    return out;
}

static bool is_valid_utf8(const std::string & s) {
    size_t i = 0;
    while (i < s.size()) {
        const uint8_t c = (uint8_t) s[i];
        size_t len;
        uint32_t cp;
        if (c < 0x80)              { len = 1; cp = c; }
        else if ((c & 0xE0) == 0xC0) { len = 2; cp = c & 0x1F; }
        else if ((c & 0xF0) == 0xE0) { len = 3; cp = c & 0x0F; }
        else if ((c & 0xF8) == 0xF0) { len = 4; cp = c & 0x07; }
        else return false;
        if (i + len > s.size()) return false;
        for (size_t j = 1; j < len; ++j) {
            const uint8_t cc = (uint8_t) s[i + j];
            if ((cc & 0xC0) != 0x80) return false;
            cp = (cp << 6) | (cc & 0x3F);
        }
        if ((len == 2 && cp < 0x80) || (len == 3 && cp < 0x800) || (len == 4 && cp < 0x10000) || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) {
            return false;
        }
        i += len;
    }
    return true;
}

static std::string escape_for_print(const std::string & s) {
    std::string out;
    for (const char c : s) {
        const uint8_t u = (uint8_t) c;
        if (c == '\n') out += "\\n";
        else if (c == '\t') out += "\\t";
        else if (c == '\r') out += "\\r";
        else if (u < 0x20 || u == 0x7F) { char b[8]; snprintf(b, sizeof(b), "\\x%02x", u); out += b; }
        else out += c;
    }
    if (out.size() > 120) {
        out = out.substr(0, 117) + "...";
    }
    return out;
}

static std::vector<std::string> read_lines(const std::string & path) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        fprintf(stderr, "error: cannot open %s\n", path.c_str());
        exit(2);
    }
    std::stringstream ss;
    ss << in.rdbuf();
    const std::string all = ss.str();
    std::vector<std::string> lines;
    size_t start = 0;
    while (start < all.size()) {
        size_t end = all.find('\n', start);
        if (end == std::string::npos) end = all.size();
        lines.push_back(all.substr(start, end - start));
        start = end + 1;
    }
    return lines;
}

static std::vector<std::vector<token_t>> read_expected(const std::string & path) {
    std::vector<std::vector<token_t>> result;
    for (const std::string & line : read_lines(path)) {
        std::vector<token_t> ids;
        std::string cur;
        for (const char c : line) {
            if (c >= '0' && c <= '9') {
                cur += c;
            } else if (c == '-' ) {
                cur += c;
            } else {
                if (!cur.empty()) { ids.push_back((token_t) std::stol(cur)); cur.clear(); }
            }
        }
        if (!cur.empty()) ids.push_back((token_t) std::stol(cur));
        result.push_back(std::move(ids));
    }
    return result;
}

static std::string ids_to_string(const std::vector<token_t> & ids) {
    std::string s = "[";
    for (size_t i = 0; i < ids.size(); ++i) {
        if (i) s += ", ";
        s += std::to_string(ids[i]);
    }
    return s + "]";
}

int main(int argc, char ** argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s <model.gguf> [expected.parse.txt] [expected.noparse.txt]\n", argv[0]);
        return 2;
    }
    const std::string model_path = argv[1];
    const char * corpus_env = std::getenv("IIAN_TOKENIZER_CORPUS");
    const std::string corpus_path = corpus_env ? corpus_env : IIAN_TOKENIZER_CORPUS;

    // ---- load vocab from GGUF metadata only ----
    gguf_init_params params = { /*no_alloc=*/true, /*ctx=*/nullptr };
    gguf_context * gguf = gguf_init_from_file(model_path.c_str(), params);
    if (!gguf) {
        fprintf(stderr, "error: cannot read gguf %s\n", model_path.c_str());
        return 2;
    }
    std::unique_ptr<iian::Tokenizer> tok;
    try {
        tok = iian::Tokenizer::from_gguf(gguf);
    } catch (const std::exception & e) {
        fprintf(stderr, "error: from_gguf failed: %s\n", e.what());
        return 2;
    }
    gguf_free(gguf); // the tokenizer must not depend on the gguf context after construction

    const auto & sp = tok->special();
    printf("model: %s\n", model_path.c_str());
    printf("vocab: type=%s pre=%s n_tokens=%d bos=%d eos=%d eot=%d nl=%d add_bos=%d add_eos=%d\n",
        tok->type_name().c_str(), tok->pre_type_name().c_str(), tok->n_tokens(), sp.bos, sp.eos, sp.eot, sp.nl,
        (int) sp.add_bos, (int) sp.add_eos);

    std::vector<std::string> corpus;
    for (const std::string & raw : read_lines(corpus_path)) {
        corpus.push_back(unescape(raw));
    }
    printf("corpus: %zu entries from %s\n", corpus.size(), corpus_path.c_str());
    CHECK(corpus.size() >= 40, "corpus too small: %zu", corpus.size());

    // ---- (a) round trip ----
    printf("[a] round trip encode -> decode\n");
    {
        const bool expect_equal = tok->type() == iian::VocabType::BPE; // SPM/WPM/UGM normalize the input
        for (size_t i = 0; i < corpus.size(); ++i) {
            const std::string & text = corpus[i];
            for (const bool parse_special : { true, false }) {
                std::vector<token_t> toks;
                try {
                    toks = tok->encode(text, sp.add_bos, parse_special);
                } catch (const std::exception & e) {
                    CHECK(false, "line %zu: encode threw: %s", i + 1, e.what());
                    continue;
                }
                if (!text.empty()) {
                    CHECK(!toks.empty(), "line %zu: empty tokenization for non-empty text", i + 1);
                }
                const std::string back = tok->decode(toks, /*remove_special=*/true, /*unparse_special=*/true);
                if (expect_equal && is_valid_utf8(text)) {
                    CHECK(back == text, "line %zu (parse_special=%d): round trip mismatch\n    in : '%s'\n    out: '%s'",
                        i + 1, (int) parse_special, escape_for_print(text).c_str(), escape_for_print(back).c_str());
                }
            }
        }
    }

    // ---- (b) exact ids vs llama-tokenize ----
    for (int a = 2; a < argc && a <= 3; ++a) {
        const bool parse_special = (a == 2);
        printf("[b] exact ids vs llama-tokenize (%s, parse_special=%d)\n", argv[a], (int) parse_special);
        const auto expected = read_expected(argv[a]);
        CHECK(expected.size() == corpus.size(), "expected file has %zu lines, corpus has %zu", expected.size(), corpus.size());
        const size_t n = std::min(expected.size(), corpus.size());
        size_t n_match = 0;
        for (size_t i = 0; i < n; ++i) {
            const auto toks = tok->encode(corpus[i], sp.add_bos, parse_special);
            if (toks == expected[i]) {
                n_match++;
            } else {
                CHECK(false, "line %zu: ids differ\n    text: '%s'\n    iian: %s\n    ref : %s", i + 1,
                    escape_for_print(corpus[i]).c_str(), ids_to_string(toks).c_str(), ids_to_string(expected[i]).c_str());
            }
        }
        printf("    %zu/%zu lines match exactly\n", n_match, n);
        CHECK(n_match == n, "%zu/%zu id mismatches", n - n_match, n);
    }

    // ---- (c) incremental detokenizer ----
    printf("[c] incremental detokenizer\n");
    {
        // c1: streaming over every corpus line must reproduce decode() and never emit a partial UTF-8 sequence
        for (size_t i = 0; i < corpus.size(); ++i) {
            const auto toks = tok->encode(corpus[i], sp.add_bos, true);
            for (const bool skip_special : { true, false }) {
                iian::IncrementalDetokenizer det(*tok, skip_special);
                std::string acc;
                for (const token_t t : toks) {
                    const std::string piece = det.push(t);
                    if (is_valid_utf8(corpus[i])) {
                        CHECK(is_valid_utf8(piece), "line %zu: push() emitted a partial UTF-8 sequence", i + 1);
                    }
                    acc += piece;
                }
                acc += det.finish();
                const std::string ref = tok->decode(toks, /*remove_special=*/false, /*unparse_special=*/!skip_special);
                CHECK(acc == ref, "line %zu (skip_special=%d): incremental != decode\n    inc: '%s'\n    dec: '%s'", i + 1,
                    (int) skip_special, escape_for_print(acc).c_str(), escape_for_print(ref).c_str());
                CHECK(det.text() == acc, "line %zu: text() != accumulated output", i + 1);
            }
        }

        // c2: byte tokens splitting a multi-byte character: nothing is emitted until the sequence completes
        std::map<uint8_t, token_t> byte_tok;
        for (token_t id = 0; id < tok->n_tokens(); ++id) {
            const std::string piece = tok->token_to_piece(id, true);
            if (piece.size() == 1 && (uint8_t) piece[0] >= 0x80 && byte_tok.count((uint8_t) piece[0]) == 0) {
                byte_tok[(uint8_t) piece[0]] = id;
            }
        }
        // every continuation byte and every UTF-8 lead byte up to U+3FFFF must exist as a byte token
        // (vocabs may legitimately lack tokens for bytes that never occur in valid UTF-8, e.g. C0/C1/F5-FF)
        for (int b = 0x80; b <= 0xF0; ++b) {
            if (b == 0xC0 || b == 0xC1) continue;
            CHECK(byte_tok.count((uint8_t) b) == 1, "missing single-byte token for byte 0x%02X", b);
        }
        printf("    %zu high byte tokens found\n", byte_tok.size());
        const std::vector<std::string> samples = { "é", "한", "😀", "日", "한글😀é" };
        for (const std::string & s : samples) {
            std::vector<token_t> toks;
            bool ok = true;
            for (const char c : s) {
                const auto it = byte_tok.find((uint8_t) c);
                if (it == byte_tok.end()) { ok = false; break; }
                toks.push_back(it->second);
            }
            CHECK(ok, "no byte token for some byte of '%s'", s.c_str());
            if (!ok) continue;

            iian::IncrementalDetokenizer det(*tok, true);
            std::string acc;
            size_t char_start = 0;
            for (size_t k = 0; k < s.size(); ++k) {
                const std::string out = det.push(toks[k]);
                // a character is complete when the next byte is not a continuation byte (or at end)
                const bool complete = (k + 1 == s.size()) || (((uint8_t) s[k + 1] & 0xC0) != 0x80);
                if (complete) {
                    CHECK(out == s.substr(char_start, k + 1 - char_start), "'%s' byte %zu: expected char emit, got '%s'", s.c_str(), k, escape_for_print(out).c_str());
                    char_start = k + 1;
                } else {
                    CHECK(out.empty(), "'%s' byte %zu: expected hold-back, got '%s'", s.c_str(), k, escape_for_print(out).c_str());
                }
                acc += out;
            }
            acc += det.finish();
            CHECK(acc == s, "byte-token stream for '%s' produced '%s'", s.c_str(), escape_for_print(acc).c_str());
            CHECK(tok->decode(toks, false, false) == s, "decode() of byte tokens for '%s' != input", s.c_str());
        }

        // c3: truncated sequence at the end is flushed raw by finish()
        {
            iian::IncrementalDetokenizer det(*tok, true);
            const std::string han = "한"; // ED 95 9C
            std::string acc = det.push(byte_tok[(uint8_t) han[0]]);
            acc += det.push(byte_tok[(uint8_t) han[1]]);
            CHECK(acc.empty(), "truncated sequence must be held back");
            acc += det.finish();
            CHECK(acc == han.substr(0, 2), "finish() must flush held-back bytes raw");
        }
    }

    // ---- (d) special tokens ----
    printf("[d] special tokens\n");
    {
        CHECK(sp.eos != iian::TOKEN_NULL, "eos missing");
        CHECK(tok->is_eog(sp.eos), "eos is not eog");
        CHECK(!tok->is_eog(iian::TOKEN_NULL), "TOKEN_NULL must not be eog");
        if (sp.eot != iian::TOKEN_NULL) {
            CHECK(tok->is_eog(sp.eot), "eot is not eog");
        }
        CHECK(sp.nl != iian::TOKEN_NULL, "newline token missing");
        CHECK(tok->token_to_piece(sp.nl, false) == "\n", "nl token piece != '\\n'");

        const token_t im_start = tok->text_to_token("<|im_start|>");
        if (im_start != iian::TOKEN_NULL) {
            CHECK(tok->is_control(im_start), "<|im_start|> not control");
            CHECK(tok->token_attr(im_start) & iian::TOKEN_ATTR_CONTROL, "<|im_start|> attr not CONTROL");
            CHECK(tok->token_text(im_start) == "<|im_start|>", "token_text mismatch");
            CHECK(tok->token_to_piece(im_start, false).empty(), "control token must be hidden when special=false");
            CHECK(tok->token_to_piece(im_start, true) == "<|im_start|>", "control token must render when special=true");
            const auto one = tok->encode("<|im_start|>", false, true);
            CHECK(one.size() == 1 && one[0] == im_start, "parse_special=true must yield the single special id (got %zu tokens)", one.size());
            const auto many = tok->encode("<|im_start|>", false, false);
            CHECK(many.size() > 1, "parse_special=false must not produce the special id");
            for (const token_t t : many) {
                CHECK(t != im_start, "parse_special=false leaked special id");
            }
            const std::string hidden = tok->decode(one, false, false);
            CHECK(hidden.empty(), "decode(unparse_special=false) must drop control tokens, got '%s'", hidden.c_str());
        }
        CHECK(tok->text_to_token("<|definitely_not_a_token|>") == iian::TOKEN_NULL, "bogus text_to_token");
        CHECK(!tok->chat_template().empty(), "chat_template missing");
        CHECK(tok->chat_template("no-such-variant").empty(), "unknown chat_template variant must be empty");
        CHECK(tok->token_to_piece(-1, true).empty() && tok->token_to_piece(tok->n_tokens(), true).empty(), "out-of-range token_to_piece");
        CHECK(!tok->is_control(-1) && !tok->is_byte(tok->n_tokens() + 5), "out-of-range is_control/is_byte");

        // remove_special strips BOS/EOS only when the model adds them
        if (sp.add_bos && sp.bos != iian::TOKEN_NULL) {
            const auto toks = tok->encode("hi", true, true);
            CHECK(!toks.empty() && toks[0] == sp.bos, "add_special did not prepend BOS");
            CHECK(tok->decode(toks, true, true).find(tok->token_text(sp.bos)) == std::string::npos, "remove_special left BOS");
        }
    }

    printf("summary: %d checks passed, %d failed\n", g_pass, g_fail);
    return g_fail == 0 ? 0 : 1;
}
